[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "trinidi"
authors = [{name = "Thilo Balke", email = "thilo.balke@gmail.com"}]
dynamic = ["version", "description"]
